apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-server
  namespace: default
  labels:
    app: helloworld-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-server
  template:
    metadata:
      namespace: default
      labels:
        app: helloworld-server
        spiffe.io/spire-managed-identity: "true"  # SPIRE에 의해 자동으로 SPIFFE ID 생성
    spec:
      containers:
      - name: helloworld-server
        image: localhost:10000/helloworld-server:mtls
        imagePullPolicy: Always
        args: ["--addr", ":8123"]
        # (svid 있는 경로)
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///tmp/spiffe-certs/socket"
        # 컨테이너 내부 경로
        volumeMounts:
        # - name: spire-agent-socket-dir
        #   mountPath: /run/custom/spiffe-uds-path
        #   readOnly: true
        # Custom
        - name: spiffe-csi
          mountPath: /tmp/spiffe-certs
          readOnly: true
      # 실제 spire-agent의 socket_path (노드 안)
      volumes:
      # - name: spire-agent-socket-dir
      #   hostPath:
      #     path: /run/secrets/workload-spiffe-uds
      #     type: DirectoryOrCreate
      - name: spiffe-csi
        csi:
          driver: csi.spiffe.io
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-server
  namespace: default
spec:
  selector:
    app: helloworld-server  
  type: LoadBalancer
  ports:
  - name: api
    port: 8123
    targetPort: 8123
    protocol: TCP
